content:
  resources:
    gold:
      name: Gold
      description: A valuable resource
      initial: 1000
    money:
      name: Money
      description: A main currency
      initial: 1000
    gold_coin:
      name: Gold Coin
      description: A rare gold coin

  buildings:
    pan:
      name: Gold Pan
      description: A simple tool for panning gold from rivers
      cost:
        money: 5
      initial: 1
      effects:
        - type: yield
          target: gold
          expression: 10 * 1.3 * pan
    sluice:
      name: Sluice Box
      description: An efficient way to separate gold from sediment
      cost:
        money: 50
        gold: 5
      effects:
        - type: yield
          target: gold
          expression: 20 * 1.3 * sluice
    mine:
      name: Gold Mine
      description: A deep mine for extracting gold from the earth
      cost:
        money: 500
        gold: 50
      effects:
        - type: yield
          target: gold
          expression: 30 * 1.3 * mine
    bank:
      name: Bank
      description: Your own bank
      cost:
        gold: 5000
      effects:
        - type: yield
          target: money
          expression: 100 * 1.3 * bank
    tower:
      name: Tower
      description: Your own tower
      cost:
        gold: 50000
      effects:
        - type: yield
          target: money
          expression: 1000 * 1.3 * tower
  upgrades:
    prospecting_skill:
      name: Prospecting Skill
      description: Improve your ability to find gold
      cost:
        money: 20
      effects:
        - type: multiply
          target: gold
          value: 1.5
    mining_equipment:
      name: Mining Equipment
      description: Better tools for more efficient gold extraction
      cost:
        money: 100
        gold: 10
      effects:
        - type: multiply
          target: gold
          value: 2
    refinery_tech:
      name: Refinery Technology
      description: Advanced technology for processing gold ore
      cost:
        money: 1000
        gold: 100
      effects:
        - type: multiply
          target: gold
          value: 3
  achievements:
    novice_prospector:
      name: Novice Prospector
      description: Pan your first gold nugget
      reqs:
        - gold >= 1
      effects:
        - type: multiply
          target: gold
          value: 10
    prospector:
      name: Prospector
      description: Pan 10 gold nuggets
      reqs:
        - gold >= 1
    gold_rush_fever:
      name: Gold Rush Fever
      description: Accumulate 100 gold
      reqs:
        - gold >= 1
    mining_magnate:
      name: Mining Magnate
      description: Own 5 of each type of mining operation
      reqs:
        - gold >= 1

  shinies:
    gold_coin_shiny:
      name: Large Gold Nugget
      description: You've stumbled upon a large gold nugget!
      frequency: 300
      duration: -1
      effects:
        - type: grant
          target: gold_coin
          value: 10

#  others:
#    prestige:
#      name: Invest in New Territory
#      description: Start fresh in a new, more promising territory
#      cost:
#        gold: 1000
#      effects:
#        - type: multiply
#          target: gold
#          value: 1.1
#        - type: reset
#          target: all
